In [3]:
import pandas as pd 


import os 

print(os.getcwd())

C:\Users\Darshil parikh

In [8]:
project= pd.read_csv("cosmetic shop data.csv")

project

,Bill_ID,Shop_Name,Date,Customer_ID,Gender,Product,Category,Qty,Unit_Price,Revenue,Discount,Final_Amount,Payment_Mode,Customer_Type,Salesperson
0,B101,Glow & Gift Shop,10-02-2026,C501,Female,Kisra Soap,Skin Care,5,120,600,0,600,UPI,Repeat,Aarav
1,B102,Glow & Gift Shop,11-02-2026,C502,Female,Face Serum,Skin Care,1,1200,1200,100,1100,UPI,New,Vivaan
2,B103,Chic Cosmetics,11-02-2026,C503,Male,Shaving Cream,Grooming,2,180,360,20,340,Cash,New,Ananya
3,B104,Glow & Gift Shop,12-02-2026,C501,Female,Lipstick,Makeup,1,450,450,0,450,UPI,Repeat,Aarav
4,B105,Chic Cosmetics,12-02-2026,C504,Female,Kisra Soap,Skin Care,4,120,480,50,430,Cash,New,Meera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,B2422,Chic Cosmetics,23-06-2026,C522,Female,Kisra Soap,Skin Care,4,120,480,0,480,UPI,Repeat,Ananya
2871,B2457,Chic Cosmetics,25-06-2026,C2319,Female,Kajal,Makeup,4,200,800,0,800,UPI,New,Meera
2872,B2621,Chic Cosmetics,09-07-2026,C550,Male,Shaving Cream,Grooming,4,180,720,20,700,UPI,Repeat,Aarav
2873,B2786,Chic Cosmetics,18-07-2026,NaN,Female,Face Serum,Skin Care,1,1200,1200,20,1180,Cash,Repeat,Sai
2874,B2453,Glow & Gift Shop,26-06-2026,C2755,Female,Kisra Soap,Skin Care,9,120,1080,20,1060,Card,New,Aarav

In [10]:
project.head(10)
project.head(115)

,Bill_ID,Shop_Name,Date,Customer_ID,Gender,Product,Category,Qty,Unit_Price,Revenue,Discount,Final_Amount,Payment_Mode,Customer_Type,Salesperson
0,B101,Glow & Gift Shop,10-02-2026,C501,Female,Kisra Soap,Skin Care,5,120,600,0,600,UPI,Repeat,Aarav
1,B102,Glow & Gift Shop,11-02-2026,C502,Female,Face Serum,Skin Care,1,1200,1200,100,1100,UPI,New,Vivaan
2,B103,Chic Cosmetics,11-02-2026,C503,Male,Shaving Cream,Grooming,2,180,360,20,340,Cash,New,Ananya
3,B104,Glow & Gift Shop,12-02-2026,C501,Female,Lipstick,Makeup,1,450,450,0,450,UPI,Repeat,Aarav
4,B105,Chic Cosmetics,12-02-2026,C504,Female,Kisra Soap,Skin Care,4,120,480,50,430,Cash,New,Meera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,B211,Glow & Gift Shop,08-04-2026,C564,Female,Kajal,Makeup,1,200,200,0,200,UPI,New,Ananya
111,B212,Chic Cosmetics,08-04-2026,C565,Female,Hair Mask,Hair Care,1,550,550,50,500,Cash,New,Sai
112,B213,Glow & Gift Shop,09-04-2026,C508,Female,Kisra Soap,Skin Care,5,120,600,20,580,UPI,Repeat,Vivaan
113,B214,Chic Cosmetics,09-04-2026,C566,Female,Lipstick,Makeup,1,450,450,0,450,UPI,New,Meera
114,B215,Glow & Gift Shop,10-04-2026,C567,Male,Perfume,Fragrance,2,950,1900,150,1750,UPI,New,Aarav

In [11]:
project.columns

Index(['Bill_ID', 'Shop_Name', 'Date', 'Customer_ID', 'Gender', 'Product',
       'Category', 'Qty', 'Unit_Price', 'Revenue', 'Discount', 'Final_Amount',
       'Payment_Mode', 'Customer_Type', 'Salesperson'],
      dtype='object')

In [12]:
project.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2875 entries, 0 to 2874
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Bill_ID        2875 non-null   object
 1   Shop_Name      2875 non-null   object
 2   Date           2875 non-null   object
 3   Customer_ID    2762 non-null   object
 4   Gender         2875 non-null   object
 5   Product        2875 non-null   object
 6   Category       2875 non-null   object
 7   Qty            2875 non-null   int64
 8   Unit_Price     2875 non-null   int64
 9   Revenue        2875 non-null   int64
 10  Discount       2875 non-null   int64
 11  Final_Amount   2875 non-null   int64
 12  Payment_Mode   2875 non-null   object
 13  Customer_Type  2875 non-null   object
 14  Salesperson    2875 non-null   object
dtypes: int64(5), object(10)
memory usage: 337.0+ KB

In [13]:
project["Date"] = pd.to_datetime(
    project["Date"],
    format="%d-%m-%Y"
)

In [15]:
project.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2875 entries, 0 to 2874
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Bill_ID        2875 non-null   object
 1   Shop_Name      2875 non-null   object
 2   Date           2875 non-null   datetime64[ns]
 3   Customer_ID    2762 non-null   object
 4   Gender         2875 non-null   object
 5   Product        2875 non-null   object
 6   Category       2875 non-null   object
 7   Qty            2875 non-null   int64
 8   Unit_Price     2875 non-null   int64
 9   Revenue        2875 non-null   int64
 10  Discount       2875 non-null   int64
 11  Final_Amount   2875 non-null   int64
 12  Payment_Mode   2875 non-null   object
 13  Customer_Type  2875 non-null   object
 14  Salesperson    2875 non-null   object
dtypes: datetime64[ns](1), int64(5), object(9)
memory usage: 337.0+ KB

In [18]:
project.isnull().sum()

Bill_ID            0
Shop_Name          0
Date               0
Customer_ID      113
Gender             0
Product            0
Category           0
Qty                0
Unit_Price         0
Revenue            0
Discount           0
Final_Amount       0
Payment_Mode       0
Customer_Type      0
Salesperson        0
dtype: int64

In [19]:
project.duplicated().sum()

np.int64(25)

In [20]:
project = project.drop(
    columns=["Unnamed: 15", "Unnamed: 16"],
    errors="ignore"
)

In [21]:
project.duplicated().sum()

np.int64(25)

In [22]:
project = project.drop_duplicates()

In [23]:
project.duplicated().sum()

np.int64(0)

In [24]:
project.columns

Index(['Bill_ID', 'Shop_Name', 'Date', 'Customer_ID', 'Gender', 'Product',
       'Category', 'Qty', 'Unit_Price', 'Revenue', 'Discount', 'Final_Amount',
       'Payment_Mode', 'Customer_Type', 'Salesperson'],
      dtype='object')

In [27]:
project['Customer_ID'] = project['Customer_ID'].fillna('unknown')

project['Customer_ID'].isnull().sum()

np.int64(0)

In [29]:
project.columns

Index(['Bill_ID', 'Shop_Name', 'Date', 'Customer_ID', 'Gender', 'Product',
       'Category', 'Qty', 'Unit_Price', 'Revenue', 'Discount', 'Final_Amount',
       'Payment_Mode', 'Customer_Type', 'Salesperson'],
      dtype='object')

In [30]:
(project["Qty"] * project["Unit_Price"]).equals(project["Revenue"])

True

In [31]:
(project["Revenue"] - project["Discount"]).equals(project["Final_Amount"])

True

In [33]:
project["Month"] = project["Date"].dt.month_name()
project["Year"] = project["Date"].dt.year
project["Quarter"] = project["Date"].dt.quarter

In [34]:
project

,Bill_ID,Shop_Name,Date,Customer_ID,Gender,Product,Category,Qty,Unit_Price,Revenue,Discount,Final_Amount,Payment_Mode,Customer_Type,Salesperson,Month,Year,Quarter
0,B101,Glow & Gift Shop,2026-02-10,C501,Female,Kisra Soap,Skin Care,5,120,600,0,600,UPI,Repeat,Aarav,February,2026,1
1,B102,Glow & Gift Shop,2026-02-11,C502,Female,Face Serum,Skin Care,1,1200,1200,100,1100,UPI,New,Vivaan,February,2026,1
2,B103,Chic Cosmetics,2026-02-11,C503,Male,Shaving Cream,Grooming,2,180,360,20,340,Cash,New,Ananya,February,2026,1
3,B104,Glow & Gift Shop,2026-02-12,C501,Female,Lipstick,Makeup,1,450,450,0,450,UPI,Repeat,Aarav,February,2026,1
4,B105,Chic Cosmetics,2026-02-12,C504,Female,Kisra Soap,Skin Care,4,120,480,50,430,Cash,New,Meera,February,2026,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2870,B2422,Chic Cosmetics,2026-06-23,C522,Female,Kisra Soap,Skin Care,4,120,480,0,480,UPI,Repeat,Ananya,June,2026,2
2871,B2457,Chic Cosmetics,2026-06-25,C2319,Female,Kajal,Makeup,4,200,800,0,800,UPI,New,Meera,June,2026,2
2872,B2621,Chic Cosmetics,2026-07-09,C550,Male,Shaving Cream,Grooming,4,180,720,20,700,UPI,Repeat,Aarav,July,2026,3
2873,B2786,Chic Cosmetics,2026-07-18,unknown,Female,Face Serum,Skin Care,1,1200,1200,20,1180,Cash,Repeat,Sai,July,2026,3
2874,B2453,Glow & Gift Shop,2026-06-26,C2755,Female,Kisra Soap,Skin Care,9,120,1080,20,1060,Card,New,Aarav,June,2026,2

In [35]:
project.to_csv("hansa novelty_cleaned.csv", index=False)